---
title: "DATA 607 - Project 1 - WNBA ELO Ratings"
author: "Kailot C. Harris"
date: "2026/09/20"
format: html
editor: visual
theme:
  dark: darkly
  light: flatly
---

# Introduction and Overview

In this project, the Elo rating methodology, which was developed to rank Chess players by Arpad Elo, will be applied to WNBA teams. Data will be sourced from the [wehoop R package](https://wehoop.sportsdataverse.org/). A convention established by the [FiveThirtyEight](https://fivethirtyeight.com) blog, and repeated in this [article](https://nicidob.github.io/nba_elo/) applying Elo ratings to NBA teams, is to start with a baseline value of 1300 for each team.

Anticipated challenges involve maintaining a reasonable scale: WNBA data exists extending back to 1997, and computing 29 seasons of Elo ratings may prove cumbersome if an efficient and repeatable architecture is not implemented from the start. The 2025 season will be used as a baseline from which the methods can be extended backward to cover the entire WNBA history, if practical. The 2025 season is the most recently resolved regular season. Other anticipated challenges may arise when visualizing the results of this analysis. A potential graph could compare Elo ratings vs time for a select group of teams.

# Adaptation

The original project assignment, related to a chess tournament, asked for specific outputs in a .csv file (e.g. player name, player state, total number of points, player pre-rating, and average opponent rating). For this adapted project, the output .csv file will contain columns for: team name, total wins, final Elo rating, and opponents' average Elo rating.

In the context of a single WNBA season, the last metric (opponents' average Elo rating) is not an effective proxy for strength of schedule, due to the balanced, round-robin structure of the WNBA. There are 13 teams (as of 2025) and each team plays each opponent team 3 or 4 times total in a season, amounting to 44 total games per team. Because Elo is a zero-sum system with a baseline value, the mean rating of all teams played over the course of a season will tend toward the baseline Elo rating of 1300. If this project is extended to trace multiyear Elo rating trajectories, then the opponents' average Elo rating may hold more significance for analysis.
